drop table LUGAR CASCADE CONSTRAINTS;
drop table VIAJE CASCADE CONSTRAINTS;
drop table PASAJERO CASCADE CONSTRAINTS;


CREATE TABLE LUGAR
   (L_CODIGO VARCHAR2(10), 
	L_NOMBRE VARCHAR2(10),
	L_TIPO 	VARCHAR2(10),
	L_CLIMA VARCHAR2(10),
	L_TOTAL_HABITANTES VARCHAR2(10),
	L_DESCRIPCION VARCHAR2(10)
   );

CREATE TABLE VIAJE
   (V_CODIGO VARCHAR2(10), 
	V_FK_PASAJERO VARCHAR2(10),	
    V_FK_LUGAR VARCHAR2(10),
    V_FECHA DATE
   );
   
CREATE TABLE PASAJERO
   (P_CODIGO VARCHAR2(10), 
	P_NOMBRE VARCHAR2(10),
    P_APELLIDO VARCHAR2(10),
	P_PERFIL VARCHAR2(10),
	P_FECHA_NACIMIENTO DATE,
	P_NUM_TELEFONICO VARCHAR2(10),
	P_FK_LUGAR_PAIS_RESIDENCIA VARCHAR2(10)
   );

commit;

/* PK constraints */

ALTER TABLE LUGAR
 ADD CONSTRAINT pk_lugar
 PRIMARY KEY (L_CODIGO) ;
 
ALTER TABLE VIAJE
 ADD CONSTRAINT pk_viaje
 PRIMARY KEY (V_CODIGO,V_FK_PASAJERO,V_FK_LUGAR) ;
 
ALTER TABLE PASAJERO
 ADD CONSTRAINT pk_pasajero
 PRIMARY KEY (P_CODIGO) ;

COMMIT;

/* FK constraints */

ALTER TABLE VIAJE ADD CONSTRAINT fk_viaje_lugar
 FOREIGN KEY (V_FK_LUGAR)
 REFERENCES LUGAR (L_CODIGO) ;
 
ALTER TABLE VIAJE ADD CONSTRAINT fk_viaje_pasajero
 FOREIGN KEY (V_FK_PASAJERO)
 REFERENCES PASAJERO (P_CODIGO) ;
  
ALTER TABLE PASAJERO ADD CONSTRAINT fk_pasajero_lugar
 FOREIGN KEY (P_FK_LUGAR_PAIS_RESIDENCIA)
 REFERENCES LUGAR (L_CODIGO) ;
 
 COMMIT;
 
 