drop table ZONAURBANA CASCADE CONSTRAINTS;
drop table BLOQUECASAS CASCADE CONSTRAINTS;
drop table CASAPARTICULAR CASCADE CONSTRAINTS;
drop table PISO CASCADE CONSTRAINTS;
drop table PERSONA CASCADE CONSTRAINTS;
drop table POSEEC CASCADE CONSTRAINTS;
drop table POSEEP CASCADE CONSTRAINTS;


CREATE TABLE ZONAURBANA
   (NOMBREZONA VARCHAR2(10), 
	CATEGORIA VARCHAR2(10)	
   ) ;

CREATE TABLE BLOQUECASAS
   (CALLE VARCHAR2(10), 
	NUMERO VARCHAR2(10),	
    NPISOS number(10),
    NOMBREZONA VARCHAR2(10)
   ) ;
   
CREATE TABLE CASAPARTICULAR
   (NOMBREZONA VARCHAR2(10), 
	NUMERO VARCHAR2(10),
    M2 NUMBER(4)
   ) ;

CREATE TABLE PISO
   (CALLE VARCHAR2(20), 
	NUMERO VARCHAR2(10),
    PLANTA VARCHAR2(5),
    PUERTA VARCHAR2(10),
    M2 NUMBER(4)
   ) ;   

CREATE TABLE PERSONA
   (DNI VARCHAR2(9), 
	NOMBRE VARCHAR2(10),
    EDAD VARCHAR2(5),
    NOMBREZONA VARCHAR2(10),
    NUMCASA VARCHAR2(10),
    CALLE VARCHAR2(20), 
	NUMBLOQUE VARCHAR2(10),
    PLANTA VARCHAR2(5),
    PUERTA VARCHAR2(10)    
   ) ;

CREATE TABLE POSEEC
   (DNI VARCHAR2(9), 
	NOMBREZONA VARCHAR2(10),
    NUMCASA VARCHAR2(10)
   ) ;
   
CREATE TABLE POSEEP
   (DNI VARCHAR2(9), 
	NOMBREZONA VARCHAR2(10),
    CALLE VARCHAR2(20), 
	NUMBLOQUE VARCHAR2(10),
    PLANTA VARCHAR2(5),
    PUERTA VARCHAR2(10)  
   ) ;
commit;

/* PK constraints */

ALTER TABLE ZONAURBANA
 ADD CONSTRAINT pk_zonaurbana
 PRIMARY KEY (NOMBREZONA) ;
 
ALTER TABLE BLOQUECASAS
 ADD CONSTRAINT pk_bloquecasas
 PRIMARY KEY (CALLE,NUMERO) ;
 
ALTER TABLE CASAPARTICULAR
 ADD CONSTRAINT pk_casaparticular
 PRIMARY KEY (NOMBREZONA,NUMERO) ;

ALTER TABLE PISO
 ADD CONSTRAINT pk_piso
 PRIMARY KEY (CALLE,NUMERO,PLANTA,PUERTA) ;
 
ALTER TABLE PERSONA
 ADD CONSTRAINT pk_persona
 PRIMARY KEY (DNI) ;
 
ALTER TABLE POSEEC
 ADD CONSTRAINT pk_poseec
 PRIMARY KEY (DNI,NOMBREZONA,NUMCASA) ;

ALTER TABLE POSEEP
 ADD CONSTRAINT pk_poseep
 PRIMARY KEY (DNI,CALLE,NUMBLOQUE,PLANTA,PUERTA) ;

COMMIT;
/* FK constraints */

ALTER TABLE BLOQUECASAS ADD CONSTRAINT fk_zonaUrbana_bloquecasas
 FOREIGN KEY (NOMBREZONA)
 REFERENCES ZONAURBANA (NOMBREZONA) ;
 
ALTER TABLE CASAPARTICULAR ADD CONSTRAINT fk_zonaUrbana_casaparticular
 FOREIGN KEY (NOMBREZONA)
 REFERENCES ZONAURBANA (NOMBREZONA) ;
 
ALTER TABLE PISO ADD CONSTRAINT fk_bloquecasas_piso
 FOREIGN KEY (CALLE,NUMERO)
 REFERENCES BLOQUECASAS (CALLE,NUMERO) ;
 
ALTER TABLE PERSONA ADD CONSTRAINT fk_casaparticular_persona
 FOREIGN KEY (NOMBREZONA,NUMCASA)
 REFERENCES CASAPARTICULAR (NOMBREZONA,NUMERO); 

ALTER TABLE PERSONA ADD CONSTRAINT fk_piso_persona
 FOREIGN KEY (CALLE,NUMBLOQUE,PLANTA,PUERTA)
 REFERENCES PISO (CALLE,NUMERO,PLANTA,PUERTA); 
 
ALTER TABLE POSEEC ADD CONSTRAINT fk_casaparticular_poseec
 FOREIGN KEY (NOMBREZONA,NUMCASA)
 REFERENCES CASAPARTICULAR (NOMBREZONA,NUMERO); 

ALTER TABLE POSEEP ADD CONSTRAINT fk_piso_poseep
 FOREIGN KEY (CALLE,NUMBLOQUE,PLANTA,PUERTA)
 REFERENCES PISO (CALLE,NUMERO,PLANTA,PUERTA);  
 
 COMMIT;
 
 